### ISSUE TITLE
Etag is not implemented properly

### ISSUE THREAD

**Issue by amccool** [OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage#10]
Etag is not handled on Writes, and the Reads are generating a new Etag on every read rather than using something like a hash on the content.

https://github.com/OrleansContrib/Orleans.StorageProviders.SimpleSQLServerStorage/blob/master/Orleans.StorageProviders.SimpleSQLServerStorage/SimpleSQLServerStorage.cs#L133

**Comment by jeoffman** [comment]
Pull request #12 is a start

**Comment by amccool** [comment]
#12 has resolved the issue
